name: Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - ".github/workflows/backend.yml"

env:
  AZURE_WEBAPP_NAME: your-app-name
  NODE_VERSION: '14.x'

defaults:
  run:
    working-directory: ./backend

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build
        run: |
          npm ci
          npm run build
      
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Deploy to Webapps
        uses: azure/webapps-deploy@v2
        with: 
          app-name: rbacgrocerystore-api
          package: ./backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}