name: Deploy Backend

on:
  [push]

env:
  AZURE_WEBAPP_NAME: your-app-name
  NODE_VERSION: '14.x'

defaults:
  run:
    working-directory: ./backend

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Build
      run: |
        npm ci
        npm run build
      
  Deply:
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with: 
        app-name: grocery-store
        package: ./backend
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}