name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

env:
  REACT_APP_API_URL: https://rbachackathondemo-api-apim.azure-api.net
  REACT_APP_API_SCOPE: api://52ddc092-f584-4d40-b70e-f7babce08518/Access
  REACT_APP_TENANT_ID: 1273adef-00a3-4086-a51a-dbcce1857d36
  REACT_APP_CLIENT_ID: 7d1e3a3c-e179-42e1-91ee-8621cc0baafd
  REACT_APP_REDIRECT_URI: https://nice-sand-0211b6d1e.azurestaticapps.net

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: "api"
          output_location: "build"
