name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

env:
  REACT_APP_API_URL: https://rbachackathondemo-api-apim.azure-api.net
  REACT_APP_API_SCOPE: api://e56573a8-5614-4a07-9ed2-a33e0d14ef3d/Access
  REACT_APP_TENANT_ID: 72f988bf-86f1-41af-91ab-2d7cd011db47
  REACT_APP_CLIENT_ID: 33224d02-2517-4f98-9dd8-2780aebe57e0
  REACT_APP_REDIRECT_URI: https://nice-sand-0211b6d1e.azurestaticapps.net

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: "api"
          output_location: "build"
