name: Deploy Frontend

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

env:
  REACT_APP_API_URL: https://rbachackathondemo-apim.azure-api.net
  REACT_APP_API_SCOPE: api://5f94a453-6b1b-40a3-976a-d42e35641083/Access
  REACT_APP_TENANT_ID: 37c69493-4ec6-4e45-b438-95c643ed70e9
  REACT_APP_CLIENT_ID: 0285b654-7b24-477f-82f7-0538056348d8
  REACT_APP_REDIRECT_URI: https://nice-sand-0211b6d1e.azurestaticapps.net

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/frontend"
          api_location: "api"
          output_location: "build"
